/*
 * OpenWorldPlatform mgmt service
 *
 * OpenWorldPlatform mgmt
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Index struct {

	Version string `json:"version,omitempty"`
}

// AssertIndexRequired checks if the required fields are not zero-ed
func AssertIndexRequired(obj Index) error {
	return nil
}

// AssertRecurseIndexRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Index (e.g. [][]Index), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIndexRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIndex, ok := obj.(Index)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIndexRequired(aIndex)
	})
}
